#!/usr/bin/env bash
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### AeroSpace workspaces #####
sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6 7 8 9; do
  sketchybar --add item space.$sid left \
    --set space.$sid \
      icon="$sid" \
      icon.padding_left=10 \
      icon.padding_right=4 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=12 \
      label.y_offset=-1 \
      background.color=0x40ffffff \
      background.corner_radius=5 \
      background.height=25 \
      background.drawing=off \
      drawing=off \
      click_script="aerospace workspace $sid"
done

sketchybar --add item spaces_updater left \
           --set spaces_updater drawing=off script="$PLUGIN_DIR/aerospace.sh" \
           --subscribe spaces_updater aerospace_workspace_change front_app_switched
##### Left #####
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Right #####
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Init #####
sketchybar --update

sketchybar --trigger aerospace_workspace_change
